# image will be published to ghcr.io/<user>/<name>
name: bluecat
# description will be included in the image's metadata
description: uBlue imaged tweaked by PolyCat for AMD/Intel GPUs

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module

modules:

  - type: gnome-extensions
    install:
      - Caffeine
      - Tiling Assistant
      - AppIndicator and KStatusNotifierItem Support

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack

  - type: akmods
    base: main # if not specified, classic "main" base is used by default
    install:
      - v4l2loopback

  - type: files
    files:
      - usr:
          /usr # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system
          # in /usr/etc/ in the image. read more in files module reference.

  - type: bling
    install:
      - ublue-update # https://github.com/ublue-os/ublue-update

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://download.docker.com/linux/fedora/docker-ce.repo
      - https://copr.fedorainfracloud.org/coprs/qoijjj/vscodium/repo/fedora-%OS_VERSION%/qoijjj-vscodium-fedora-%OS_VERSION%.repo
    install:
      #- steam-devices
      #- gnome-console
      - WoeUSB
      - codium
      - python3-tkinter
      - python3-wxpython4
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

    remove:
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - gnome-shell-extension-background-logo
      #- gnome-terminal
      #- gnome-terminal-nautilus
      - nvtop

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.valvesoftware.Steam
        - org.gnome.Loupe
        - io.github.celluloid_player.Celluloid
        - com.mattjakeman.ExtensionManager
        - org.gnome.Calendar
        - com.github.tchx84.Flatseal
        - it.mijorus.gearlever
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
